// This file was automatically generated by Kmisc::registerFunctions()

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP R_plotGh(SEXP _gsPtr,SEXP _sampleName,SEXP _output);
SEXP R_getNodes(SEXP _gsPtr,SEXP _sampleName,SEXP _order,SEXP _isPath, SEXP _showHidden);
SEXP R_getNodeID(SEXP _gsPtr,SEXP _sampleName,SEXP _gatePath);
SEXP R_getParent(SEXP _gsPtr,SEXP _sampleName,SEXP _i);
SEXP R_getChildren(SEXP _gsPtr,SEXP _sampleName,SEXP _i);
SEXP R_getPopStats(SEXP _gsPtr,SEXP _sampleName,SEXP _i);
SEXP R_getCompensation(SEXP _gsPtr,SEXP _sampleName);
SEXP R_getTransformations(SEXP _gsPtr,SEXP _sampleName);
SEXP R_gating(SEXP _gsPtr,SEXP _mat,SEXP _sampleName,SEXP _gains, SEXP _nodeInd,SEXP _recompute, SEXP _extend_val, SEXP _ignore_case);
SEXP R_getGate(SEXP _gsPtr,SEXP _sampleName,SEXP _i);
SEXP R_getIndices(SEXP _gsPtr,SEXP _sampleName,SEXP _i);
SEXP R_getGateFlag(SEXP _gsPtr,SEXP _sampleName,SEXP _i);
SEXP R_addGate(SEXP _gsPtr,SEXP _sampleName,SEXP _filter,SEXP _parentID,SEXP _popName);
SEXP R_setGate(SEXP _gsPtr,SEXP _sampleName,SEXP _nodeID,SEXP _filter);
SEXP R_removeNode(SEXP _gsPtr,SEXP _sampleName,SEXP _nodeID);
SEXP R_setNodeName(SEXP _gsPtr,SEXP _sampleName,SEXP _nodeID, SEXP _newNodeName);
SEXP R_setNodeFlag(SEXP _gsPtr,SEXP _sampleName,SEXP _nodeID, SEXP _hidden);
SEXP R_parseWorkspace(SEXP _fileName,SEXP _sampleIDs,SEXP _isParseGate,SEXP _sampNloc,SEXP _xmlParserOption, SEXP _wsType, SEXP _dMode);
SEXP R_getSamples(SEXP _gsPtr);
SEXP R_NewGatingSet(SEXP _gsPtr,SEXP _sampleName,SEXP _newSampleNames,SEXP _dMode);
SEXP R_NewGatingSet_rootOnly(SEXP _sampleNames,SEXP _dMode);
SEXP R_saveGatingSet(SEXP _gsPtr,SEXP _fileName, SEXP _typeID);
SEXP R_loadGatingSet(SEXP _fileName, SEXP _typeID);
SEXP R_CloneGatingSet(SEXP _gsPtr,SEXP _samples);
SEXP R_combineGatingSet(SEXP _gsPtrs,SEXP _samples);
SEXP R_setSample(SEXP _gsPtrs,SEXP _oldName, SEXP _newName);

R_CallMethodDef callMethods[]  = {
  {"C_R_plotGh", (DL_FUNC) &R_plotGh, 3},
  {"C_R_getNodes", (DL_FUNC) &R_getNodes, 5},
  {"C_R_getNodeID", (DL_FUNC) &R_getNodeID, 3},
  {"C_R_getParent", (DL_FUNC) &R_getParent, 3},
  {"C_R_getChildren", (DL_FUNC) &R_getChildren, 3},
  {"C_R_getPopStats", (DL_FUNC) &R_getPopStats, 3},
  {"C_R_getCompensation", (DL_FUNC) &R_getCompensation, 2},
  {"C_R_getTransformations", (DL_FUNC) &R_getTransformations, 2},
  {"C_R_gating", (DL_FUNC) &R_gating, 8},
  {"C_R_getGate", (DL_FUNC) &R_getGate, 3},
  {"C_R_getIndices", (DL_FUNC) &R_getIndices, 3},
  {"C_R_getGateFlag", (DL_FUNC) &R_getGateFlag, 3},
  {"C_R_addGate", (DL_FUNC) &R_addGate, 5},
  {"C_R_setGate", (DL_FUNC) &R_setGate, 4},
  {"C_R_removeNode", (DL_FUNC) &R_removeNode, 3},
  {"C_R_setNodeName", (DL_FUNC) &R_setNodeName, 4},
  {"C_R_setNodeFlag", (DL_FUNC) &R_setNodeFlag, 4},
  {"C_R_parseWorkspace", (DL_FUNC) &R_parseWorkspace, 7},
  {"C_R_getSamples", (DL_FUNC) &R_getSamples, 1},
  {"C_R_NewGatingSet", (DL_FUNC) &R_NewGatingSet, 4},
  {"C_R_NewGatingSet_rootOnly", (DL_FUNC) &R_NewGatingSet_rootOnly, 2},
  {"C_R_saveGatingSet", (DL_FUNC) &R_saveGatingSet, 3},
  {"C_R_loadGatingSet", (DL_FUNC) &R_loadGatingSet, 2},
  {"C_R_CloneGatingSet", (DL_FUNC) &R_CloneGatingSet, 2},
  {"C_R_combineGatingSet", (DL_FUNC) &R_combineGatingSet, 2},
  {"C_R_setSample", (DL_FUNC) &R_setSample, 3},
  {NULL, NULL, 0}
};

void R_init_flowWorkspace(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

